name: Main Branch

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go-version: [1.23.1]
        os: [ubuntu-latest]
        arch: [amd64, arm64]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}

    - name: Install dependencies
      run: |
        sudo dpkg --add-architecture ${{ matrix.arch }}
        sudo apt-get update
        sudo apt-get install -y libpcap-dev:${{ matrix.arch }}
        go install golang.org/x/lint/golint@latest
        go install honnef.co/go/tools/cmd/staticcheck@latest

    - name: Run linters and tests
      env:
        GO111MODULE: on
      run: |
        GO_FILES=$(find . -iname '*.go' -type f)
        test -z $(gofmt -l $GO_FILES)
        go test -v -race ./...
        go vet ./...
        staticcheck ./...
        golint -set_exit_status $(go list ./...)

    - name: Build
      env:
        GOARCH: ${{ matrix.arch }}
        GOOS: linux
      run: |
        go build -o iot-reflector-${{ matrix.arch }}